### ISSUE TITLE
api view profiles and ingredients

### ISSUE THREAD

**Issue by harrim91** [harrim91/allergy_scanner_frontend#3]
I want to select diet profiles to apply to my account
So that the app knows which foods I want to avoid

**Comment by sitaraemilys** [comment]
forms to choose diet profiles

**Comment by harrim91** [comment]
app needs to request data from the api - GET '/diet_profiles'
display each of these profiles and the ingredients covered by them
ability to select multiple profiles
clicking save sends a post request to the api containing the selected ingredients to be saved to the profile

**Comment by marawanot** [comment]
save user preferences
later load them back and fill out form when user goes back to page
so they can see what they chose before
